### PR TITLE
Exam - Part 1

### PR DESCRIPTION
**Pull request by sara-dubrov**
I finished the first part of the exam, and started the second part. 
This is a commit of part 1 only.

BTW, the exam is very clear.

### CODE REVIEW

**Comment by doronuziel71** [comment]
Hi,
First of all - thank you.
Second - I created a branch `candidates/sara-dubrov`
Can you please change your PR to be to this branch?

**Comment by doronuziel71** [comment]
Also - I suggets you do not do Part 2 yet. I still need to think about it.

**Comment by sara-dubrov** [comment]
yes, I'm opening another PR.

**Comment by doronuziel71** [comment]
Also - ignore my previous request  - please proceed to Part 2.

**Comment by sara-dubrov** [comment]
OK, I continue with that.

**Pull request closed without merging**
