### PR TITLE
There have been completed all part`s test.

### PR DESCRIPTION
**Pull request by nikolaev13nik**

### CODE REVIEW

**Comment by doronuziel71** [comment]
Thank you will check tmrw

**Comment by doronuziel71** [comment]
Nikita,

Please do not use lombok. I understand this instrument appeal but you will not be able to use it in the job you are applying for.

So I will appreciate if you refactor your code and resubmit

**Comment by nikolaev13nik** [comment]
> Nikita,
> 
> Please do not use lombok. I understand this instrument appeal but you will not be able to use it in the job you are applying for.
> 
> So I will appreciate if you refactor your code and resubmit

**Comment by nikolaev13nik** [comment]
Doron,

I removed Lombok and made all the required changes.
Please, contact me to confirm that you saw those changes

**Comment by nikolaev13nik** [comment]
Hello Doron,
I just wanted to know if you had seen changes which I applied soon after
your comment?

**Comment by doronuziel71** [comment]
Yes I did see it. You did exaclty as I've asked. We are interviewing other candidates and are discussing things between us.
Tome or Noa will be in touch with you

**Comment by doronuziel71** [comment]
I am removing the PR not because it is not ok - just for cleaning purposes. I would appreciate if you keep your fork for a few more days at least

**Pull request closed without merging**
